[[constraint]]
  branch = "master"
  name = "github.com/armon/go-socks5"

[[constraint]]
  branch = "master"
  name = "github.com/mgutz/ansi"

[[constraint]]
  branch = "master"
  name = "github.com/weaveworks/common"

[[constraint]]
  branch = "master"
  name = "golang.org/x/net"

[[constraint]]
  branch = "master"
  name = "golang.org/x/tools"

# Prometheus deps
[[constraint]]
  branch = "master"
  name = "github.com/prometheus/common"

[[override]]
  branch = "master"
  name = "github.com/prometheus/client_golang"

[[override]]
  version = "1.2"
  name = "github.com/emicklei/go-restful"

[[override]]
  name = "k8s.io/client-go"
  revision = "3627aeb7d4f6ade38f995d2c923e459146493c7e"

[[override]]
  name = "k8s.io/apimachinery"
  revision = "75b8dd260ef0469d96d578705a87cffd0e09dab8"

[[override]]
  name = "github.com/Azure/azure-sdk-for-go"
  revision = "bd73d950fa4440dae889bd9917bff7cef539f86e"

[[override]]
  name = "github.com/Azure/go-autorest"
  revision = "8a25372bbfec739b8719a9e3987400d15ef9e179"

[[override]]
  name = "github.com/ugorji/go"
  revision = "708a42d246822952f38190a8d8c4e6b16a0e600c"


[prune]
  go-tests = true
  unused-packages = true
