[[constraint]]
  branch = "master"
  name = "github.com/armon/go-socks5"

[[constraint]]
  name = "github.com/golang/protobuf"
  version = "1.1.0"

[[constraint]]
  branch = "master"
  name = "github.com/golang/snappy"

[[constraint]]
  branch = "master"
  name = "github.com/mgutz/ansi"

[[constraint]]
  branch = "master"
  name = "github.com/weaveworks/common"

[[constraint]]
  branch = "master"
  name = "golang.org/x/net"

[[constraint]]
  branch = "master"
  name = "golang.org/x/tools"

# Prometheus deps
[[constraint]]
  name = "github.com/prometheus/prometheus"
  branch = "master"

[[constraint]]
  branch = "master"
  name = "github.com/prometheus/common"

[[override]]
  branch = "master"
  name = "github.com/prometheus/client_golang"

[[override]]
  version = "1.2"
  name = "github.com/emicklei/go-restful"

[[override]]
  name = "k8s.io/client-go"
  revision = "3627aeb7d4f6ade38f995d2c923e459146493c7e"

[[override]]
  name = "k8s.io/apimachinery"
  revision = "75b8dd260ef0469d96d578705a87cffd0e09dab8"

[[override]]
  name = "github.com/Azure/azure-sdk-for-go"
  revision = "bd73d950fa4440dae889bd9917bff7cef539f86e"

[prune]
  go-tests = true
  unused-packages = true
